build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
args:
  DYNGLANCE_REPO: https://github.com/trooperthorn/ha_app_dynglance.git
  DYNGLANCE_REF: main
